server:
  port: 9527

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: payment_1
          uri: http://localhost:8001
          predicates:
            -Path=/payment/get/**
        - id: payment_2
          uri: http://localhost:8001
          predicates:
            -Path=/payment/getport/**

eureka:
  client:
    service-url:
      defaultZone: http://Eureka7001.com:7001/eureka/,http://Eureka7002.com:7002/eureka/