spring:
  application:
    name: spring-cloud-eureka-server

server:
  port: 7001

eureka:
  instance:
    hostname: Eureka7001.com
  client:
    #eureka默认情况下,把自己当做客户端来注册自己,所以我们要禁用它 这里是服务端
    fetch-registry: false
    register-with-eureka: false #不去检索eureka服务
    serviceUrl:
      defaultZone: http://Eureka7002.com:7002/eureka/
      # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；
      #多个地址可使用 , 分隔
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

      #集群：7001 注册到 7002
     #defaultZone: http://Eureka7002.com:7002/eureka/

      #集群：7002 注册到 7001
    #defaultZone: http://Eureka7001.com:7001/eureka/